version: '3'

services:
  registry:
    image: arrowhead/agile.ro:registry
    ports:
      - "8443:8443"

  orchestrator:
    image: arrowhead/agile.ro:orchestrator
    ports:
      - "8441:8441"

  auth:
    image: arrowhead/agile.ro:auth
    ports:
      - "8445:8445"

  mqtt_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"

  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"

  database:
    #there i want to use google sheets as database, but I put for the moment mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

