version: '3'

services:
  registry:
    image: arrowhead/agile.ro:registry
    ports:
      - "8443:8443"

  orchestrator:
    image: arrowhead/agile.ro:orchestrator
    ports:
      - "8441:8441"

  auth:
    image: arrowhead/agile.ro:auth
    ports:
      - "8445:8445"

  mqtt_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"

  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=tempAndHum
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Practica123*
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=pass
